name: DOM Code Generator
on:
  push:
    branches: [ main ]
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+-[0-9a-zA-Z]+'
  workflow_dispatch: 
jobs:
  Generator:
    name: Generator
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./src
          fetch-depth: 0

      - name: Initialize
        run: |
          echo "workspace" ${{ github.workspace }}
          echo "ref name" ${{ github.ref_name }}
          echo "run number" ${{ github.run_number }}
          echo "ref type" ${{ github.ref_type }}
          echo "repository" ${{ github.repository }}

      - name: Clone Code Generator
        uses: actions/checkout@v4
        with:
          path: ./generator
          repository: ArneMaes0/Tool.DOM.Code.Generator

      - name: Build Code Generator
        run: |
          dotnet restore "./generator/Tools.DOM.Code.Generator/Tools.DOM.Code.Generator.csproj"
          dotnet build "./generator/Tools.DOM.Code.Generator/Tools.DOM.Code.Generator.csproj"
        # dotnet nuget add source "./generator/Tools.DOM.Code.Generator/bin/Debug/net8.0"

      - name: Logging
        run: |
          Get-ChildItem -Path "./generator/Tools.DOM.Code.Generator/bin"
          Get-ChildItem -Path "./generator/Tools.DOM.Code.Generator/bin/Debug"
          Get-ChildItem -Path "./generator/Tools.DOM.Code.Generator/bin/Debug/net8.0"

      - name: Create Nuget Package
        shell: cmd
        run: |
          dotnet new classlib -n Skyline.DataMiner.DOM.ResourceManagement

      - name: Rename class
        shell: cmd
        run: |
          ren Skyline.DataMiner.DOM.ResourceManagement\Class1.cs DomHelpers.cs

      - name: Update .csproj
        shell: cmd
        run: |
          (
          echo ^<Project Sdk="Microsoft.NET.Sdk"^>
          echo  ^<PropertyGroup^>
          echo    ^<TargetFramework^>net462^</TargetFramework^>
          echo    ^<ImplicitUsings^>disable^</ImplicitUsings^>
          echo    ^<Nullable^>disable^</Nullable^>
          echo    ^<AssemblyName^>Skyline.DataMiner.DOM.ResourceManagement^</AssemblyName^>
          echo    ^<RootNamespace^>Skyline.DataMiner.DOM.ResourceManagement^</RootNamespace^>
          echo    ^<PackageVersion^>1.0.0-${{ github.run_number }}^</PackageVersion^>
          echo    ^<Version^>1.0.0-${{ github.run_number }}^</Version^>
          echo    ^<PackageTags^>Skyline;DataMiner^</PackageTags^>
          echo    ^<PackageProjectUrl^>https://skyline.be^</PackageProjectUrl^>
          echo    ^<GenerateDocumentationFile^>True^</GenerateDocumentationFile^>
          echo    ^<GeneratePackageOnBuild^>True^</GeneratePackageOnBuild^>
          echo    ^<Authors^>SkylineCommunications^</Authors^>
          echo    ^<Company^>Skyline Communications^</Company^>
          echo    ^<Description^>Contains helper classes to interact with the DOM instances.^</Description^>
          echo    ^<RepositoryType^>git^</RepositoryType^>
          echo  ^</PropertyGroup^>
          echo  ^<ItemGroup^>
          echo    ^<PackageReference Include="Skyline.DataMiner.Dev.Common" Version="10.3.9" /^>
          echo  ^</ItemGroup^>
          echo ^</Project^>
          ) > Skyline.DataMiner.DOM.ResourceManagement/Skyline.DataMiner.DOM.ResourceManagement.csproj

      - name: Logging
        shell: cmd
        run: |
          type Skyline.DataMiner.DOM.ResourceManagement\Skyline.DataMiner.DOM.ResourceManagement.csproj

      - name: Generate Code
        shell: cmd
        run: |
          "./generator/Tools.DOM.Code.Generator/bin/Debug/net8.0/Skyline.DataMiner.Tools.DOM.Code.Generator.exe" --file "./src/module.json" > Skyline.DataMiner.DOM.ResourceManagement/DomHelpers.cs

      - name: Logging
        shell: cmd
        run: |
          type Skyline.DataMiner.DOM.ResourceManagement\DomHelpers.cs

      - name: Logging
        run: |
          Get-ChildItem -Path "./Skyline.DataMiner.DOM.ResourceManagement"

      - name: Build Nuget Package
        shell: cmd
        run: |
          dotnet build Skyline.DataMiner.DOM.ResourceManagement/Skyline.DataMiner.DOM.ResourceManagement.csproj

      - name: Checkout Nuget Package
        uses: actions/upload-artifact@v4
        with:
          name: DOM_Helper_Nuget
          path: "./Skyline.DataMiner.DOM.ResourceManagement/bin/Debug/Skyline.DataMiner.DOM.ResourceManagement.1.0.0-${{ github.run_number }}.nupkg"

